# Generated by Django 5.2 on 2025-04-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Inventyory',
            new_name='Inventory',
        ),
    ]
